export const GET_AUDIT_LOGS_REQUEST = 'GET_AUDIT_LOGS_REQUEST';
export const GET_AUDIT_LOGS_SUCCESS = 'GET_AUDIT_LOGS_SUCCESS';
export const GET_AUDIT_LOGS_FAILURE = 'GET_AUDIT_LOGS_FAILURE';

export const CREATE_AUDIT_LOG_REQUEST = 'CREATE_AUDIT_LOG_REQUEST';
export const CREATE_AUDIT_LOG_SUCCESS = 'CREATE_AUDIT_LOG_SUCCESS';
export const CREATE_AUDIT_LOG_FAILURE = 'CREATE_AUDIT_LOG_FAILURE';

export const CLEAR_AUDIT_ERROR = 'CLEAR_AUDIT_ERROR';